// animations.js
export const animations = {

  Emoji: [
"animations/emo1.json",
"animations/emo2.json",
"animations/emo3.json",
"animations/emo4.json",
"animations/emo5.json",
"animations/emo6.json",
"animations/emo7.json",
"animations/emo8.json",
"animations/emo9.json",
"animations/emo10.json",
"animations/emo11.json",
"animations/emo12.json",
"animations/emo13.json",
"animations/emo14.json",
"animations/emo15.json",
"animations/emo16.json",
"animations/emo17.json",
"animations/emo18.json",
"animations/emo19.json",
"animations/emo20.json",
"animations/emo21.json",
"animations/emo22.json",
"animations/emo23.json",
"animations/emo24.json",
"animations/emo25.json",
"animations/emo26.json",
"animations/emo27.json",
"animations/emo28.json",
"animations/emo29.json",
"animations/emo30.json",
"animations/emo31.json",
"animations/emo32.json",
"animations/emo33.json",
"animations/emo34.json",
"animations/emo35.json",
"animations/emo36.json",
"animations/emo37.json",
"animations/emo38.json",
"animations/emo39.json",
"animations/emo40.json",
"animations/emo41.json",
"animations/emo42.json",
"animations/emo43.json",
"animations/emo44.json",
"animations/emo45.json",
"animations/emo46.json",
"animations/emo47.json",
"animations/emo48.json",
"animations/emo49.json",
"animations/emo50.json",
"animations/emo51.json",
"animations/emo52.json",
"animations/emo53.json",
"animations/emo54.json",
"animations/emo55.json",
"animations/emo56.json",
"animations/emo57.json",
"animations/emo58.json",
"animations/emo59.json",
"animations/emo60.json",
"animations/emo61.json",
"animations/emo62.json",
"animations/emo63.json",
"animations/emo64.json",
"animations/emo65.json",
"animations/emo66.json",
"animations/emo67.json",
"animations/emo68.json",
"animations/emo69.json",
"animations/emo70.json",
"animations/emo71.json",
"animations/emo72.json",
"animations/emo73.json",
"animations/emo74.json",
"animations/emo75.json",
"animations/emo76.json",
"animations/emo77.json",
"animations/emo78.json",
"animations/emo79.json",
"animations/emo80.json",
"animations/emo81.json",
"animations/emo82.json",
"animations/emo83.json",
"animations/emo84.json",
"animations/emo85.json",
"animations/emo86.json",
"animations/emo87.json",
"animations/emo88.json",
"animations/emo89.json",
"animations/emo90.json",
"animations/emo91.json",
"animations/emo92.json",
"animations/emo93.json",
"animations/emo94.json",
"animations/emo95.json",
"animations/emo96.json",
"animations/emo97.json",


  ],

  Amor: [
  
 
  ],

  Reacoes: [
   
  ],

  Memes: [
    
  ],
};